apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multipod
  name: multipod
spec:
  containers:
  - name: maincont
    image: busybox
    command:
    - /bin/sh
    - -c
    - while true; do echo 'Hi I am from main container' >> /var/log/index.html; sleep
      5; done
    volumeMounts:
    - name: myvol
      mountPath: /var/log
  - name: nginxcont
    image: nginx
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: myvol
    emptyDir: {}
    


